name: rupee_elf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.1
  fluro: ^2.0.5
  crypto: ^3.0.3
  camera: ^0.10.5+3
  geolocator: ^9.0.2
  aws_s3_api: ^2.0.0
  adjust_sdk: ^4.33.1
  date_format: ^2.0.7
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12
  image_picker: ^1.0.2
  package_info: ^2.0.2
  devicelocale: ^0.6.0
  battery_plus: ^4.0.2
  advertising_id: ^2.4.0
  json_annotation: ^4.8.1
  pin_code_fields: ^8.0.1
  flutter_contacts: ^1.1.7+1
  device_info_plus: ^9.0.2
  pretty_dio_logger: ^1.3.1
  screen_brightness: ^0.2.2
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3
  flutter_screenutil: ^5.8.4
  facebook_app_events: ^0.19.0
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.0.4
  flutter_native_timezone: ^2.0.0
  connection_network_type: ^0.0.1
  flutter_advanced_networkimage_2: ^2.0.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - static/images/

    - static/icons/

  fonts:
    - family: IconFont
      fonts:
        - asset: static/fonts/iconfont.ttf