name: rupee_elf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluro: ^2.0.5
  flutter_advanced_networkimage_2: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - static/images/

    - static/icons/

  fonts:
    - family: IconFont
      fonts:
        - asset: static/fonts/iconfont.ttf

  

